### ISSUE TITLE
How to set header Items selectable..

### ISSUE THREAD

**Issue by kardani** [recruit-mp/android-HeaderFooterGridView#1]
Hi dear

Thanks for this class...

I used the HeaderFooterGridView and i have clickable header but when i click header of grid view nothing happend.

Please help.

Sorry for my bad English

**Comment by yhirano** [comment]
HeaderFooterGridView supports header items click.
Please see [HeaderFooterGridViewDemoActivity.java](https://github.com/recruit-mp/android-HeaderFooterGridView/blob/7fc156f2ac0f2ef4551b484def7e578d7d859d05/demo/src/main/java/jp/co/recruit_mp/android/headerfootergridviewdemo/HeaderFooterGridViewDemoActivity.java).

or such as the following

``` java
headerFooterGridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        if (position / headerFooterGridView.getNumColumns() < headerFooterGridView.getHeaderViewCount()) {
            switch (position / headerFooterGridView.getNumColumns()) {
                case 0:
                    Toast.makeText(HeaderFooterGridViewDemoActivity.this, "Tap Header 1", Toast.LENGTH_SHORT).show();
                    break;
                case 1:
                    Toast.makeText(HeaderFooterGridViewDemoActivity.this, "Tap Header 2", Toast.LENGTH_SHORT).show();
                    break;
            }
        }
    }
});
```
