### ISSUE TITLE
how to add two gridviews with header and footer in one xml ? 

### ISSUE THREAD

**Issue by engr-erum** [recruit-mp/android-HeaderFooterGridView#11]
i m unable to add "2 GRIDVIEWS using your lib i have added dependencies in gradle and fully qualifier name in xml too "  but still unable to  add two gridviews with header and footer inside linearlayout  in "VERTICAL ORIENTATION"  i m getting error that second gridview already has views

**Comment by yhirano** [comment]
Can you give me a your error project?

**Comment by engr-erum** [comment]
ok sure will post

**Comment by yhirano** [comment]
Close the issue because the post is not.
