### ISSUE TITLE
Does not seem to use the full width?

### ISSUE THREAD

**Issue by broakenmedia** [recruit-mp/android-HeaderFooterGridView#2]
http://share.joescott.me/9d55045.jpg

(Ignore the 'top 10' smaller header, that's not using this lib)

But as you can see the bar along the top, will not use the full width of the gridview, not to mention the text i set on it, is not visible?

**Comment by yhirano** [comment]
I don't know the cause of your problem, but my demo is possible it.
https://github.com/recruit-mp/android-HeaderFooterGridView/tree/master/demo

If you don't need footer, you can use HeaderGridView made by Google.
http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android-apps/4.4_r1/com/android/photos/views/HeaderGridView.java
