### ISSUE TITLE
How to add margin GridView without header/footer?

### ISSUE THREAD

**Issue by 0xBADDCAFE** [recruit-mp/android-HeaderFooterGridView#6]
[In your Example](http://tech.recruit-mp.co.jp/mobile/android-headerfootergridview/), Header has full width and GridView has margin.

![android-headerfootergridview-header-sample](https://cloud.githubusercontent.com/assets/599164/7312828/c8d927ec-ea8c-11e4-88c9-b60277ba45d3.png)

If add margin to HeaderFooterGridView, it's added to header/footer too. I want to keep header full width just like your example. Please teach how to do it?

Thanks to awesome project.

**Comment by yhirano** [comment]
下記のようなコードならヘッダが広がると思います。

``` java
// ヘッダービューを生成
View headerView = inflater.inflate(R.layout.header_view, null);
// こんな感じでヘッダー内の子ビューにコンテンツを追加していく
TextView titleView = (TextView) headerView.findViewById(R.id.title);
titleView.setText("TITLE");
// ヘッダービューをHeaderFooterGridView追加
mGridView.addHeaderView(headerView, null, false);
```

``` xml
<?xml version="1.0" encoding="utf-8"?>

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="#FFFFFF"
              android:orientation="vertical">

    <TextView
      android:id="@+id/title"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:layout_gravity="center_vertical"
      android:layout_marginLeft="4dp"
      android:layout_marginRight="4dp"/>

</LinearLayout>
```

**Comment by 0xBADDCAFE** [comment]
この時、HeaderFooterGridView の margin は設定していても広がるでしょうか、それとも HeaderFooterGridView の margin は設定していない場合の例でしょうか。

HeaderFooterGridView の margin を設定していなければ上記のコードでヘッダを広げられますが、GridView 側の margin が無くなってしまうので、そこに margin を設定する方法が無いかと考えています。

HeaderFooterGridView に margin を設定してしまうと上記のコードではヘッダが広がらないかと思いますが、特に必要な属性等があるのでしょうか。

**Comment by yhirano** [comment]
すいません、ご質問を勘違いしてました。
ご質問のお答えですが、HeaderFooterGridViewにマージンを指定した場合はヘッダは画面に対し全幅になりません。HeaderFooterGridViewの幅に制約されます（これはどうしようもない）。

上記の例でHeaderFooterGridViewの幅を超えたヘッダがあるように見えるのは、HeaderFooterGridViewはフルの幅にし、GridになるViewに左右に余白を設けてそれっぽく見せているためです。
GridになるViewは下記のような感じになります。

![gridview](https://cloud.githubusercontent.com/assets/648815/7317224/75e75f04-eab9-11e4-82fb-fe997a0662b2.png)
↑ コンテンツを表示する部分に左右上下にマージンを入れています。

**Comment by 0xBADDCAFE** [comment]
ありがとうございます。
2 行レイアウトだと確かに個々の VIew の margin を調節することで可能でした、3 行レイアウトで試していたので気付きませんでした。

納得したので閉じさせていただきます。

**Comment by yhirano** [comment]
3行レイアウト左右にマージンをあけたい場合、Gridの位置を判定してコード上でマージンを動的に変更するくらいしかないかと思います。
でもそこまでするならListViewで似た感じのViewを作るほうが楽かもしれません。
