### ISSUE TITLE
multi grid view

### ISSUE THREAD

**Issue by yfsx** [recruit-mp/android-HeaderFooterGridView#8]
it is possible to add other grid view (in this case unscrollabe grid view) to header and / or footer? 
thanks :)

**Comment by yhirano** [comment]
Although GridView can be added to the header/footer of HeaderFooterGridView due to GridView is also view, **probably you can not meet the your needs**.
I recommend that create your custom view for header/footer and add it, or custom display for each item view in the GridView.

**Comment by yfsx** [comment]
actually i can set gridview to the header and footer but i cant set the height of the header and footer grid, and it looks like this

<img width="482" alt="screen shot 2015-08-27 at 2 28 45 pm" src="https://cloud.githubusercontent.com/assets/10009357/9514910/f8472fe0-4cc7-11e5-82bc-b29f5fcbfed1.png">

it looks like it doesn't meet what i needs

thanks, great lib btw!

**Comment by yhirano** [comment]
In order to meet your needs, you might use [StickyGridHeaders](https://github.com/TonicArtos/StickyGridHeaders).
I think not appropriate to use HeaderFooterGridView in order to meet your needs.

Thanks!

**Comment by yfsx** [comment]
i tried before, but the project is abandoned haha 

thanks!!

**Comment by engr-erum** [comment]
@yfsx the same requirement i need this is called sections  Gridview with header and footer with the use of stickyGridHeaders   i m  unable to  provide footer for every section have u found solution ?
